//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharikiApp.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BalloonType
    {
        public BalloonType()
        {
            this.Balloons = new HashSet<Balloon>();
        }
    
        public int BalloonTypeId { get; set; }
        public Nullable<int> Order { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Balloon> Balloons { get; set; }
    }
}
